// Require library mongoose
const mongoose = require(`mongoose`);

// Require environment variables
const dotenv = require("dotenv");
dotenv.config(); // Load .env variables into process.env

// Get the MongoDB connection string from environment variables
const mongoDb = process.env.MONGO_DB;

// Require the Product model
const Product = require(`../models/product.model`);

// Create an array of seed product documents
const products = [
    {
        name: "Avocado Toast",
        price: 7,
        description: "Whole-grain toast with avocado, cherry tomatoes, and a drizzle of olive oil.",
        category: "breakfast",
        ingredients: ["Whole-grain bread", "Avocado", "Cherry tomatoes", "Olive oil", "Salt"],
        image: "/img/freepik__candid-image-photography-natural-textures-highly-r__85082.jpeg",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Bacon & Eggs Platter",
        price: 8,
        description: "A classic breakfast plate with crispy bacon, sunny-side-up eggs, and toast.",
        category: "breakfast",
        ingredients: ["Bacon", "Eggs", "Toast", "Butter"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Vegetable Omelette",
        price: 8,
        description: "Delicious omelette made with mushrooms, spinach, and cheese.",
        category: "breakfast",
        ingredients: ["Eggs", "Mushrooms", "Spinach", "Cheese"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Pancakes with Honey",
        price: 6,
        description: "Fluffy pancakes served with honey and fresh fruits.",
        category: "breakfast",
        ingredients: ["Flour", "Eggs", "Milk", "Honey", "Fresh fruits"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Yogurt with Granola",
        price: 4,
        description: "Natural yogurt with crunchy granola and seasonal fruits.",
        category: "breakfast",
        ingredients: ["Yogurt", "Granola", "Seasonal fruits"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Eggs Benedict",
        price: 12,
        description: "Poached eggs on toasted English muffins with ham and creamy hollandaise sauce.",
        category: "brunch",
        ingredients: ["Eggs", "English muffin", "Ham", "Hollandaise sauce"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Avocado and Feta Salad",
        price: 10,
        description: "Fresh avocado slices served with crumbled feta cheese, cherry tomatoes, and arugula.",
        category: "brunch",
        ingredients: ["Avocado", "Feta cheese", "Cherry tomatoes", "Arugula", "Olive oil"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Chicken and Waffles",
        price: 14,
        description: "Crispy fried chicken served with fluffy waffles and maple syrup.",
        category: "brunch",
        ingredients: ["Chicken", "Waffles", "Maple syrup", "Butter"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Spinach and Goat Cheese Quiche",
        price: 9,
        description: "Savory quiche filled with fresh spinach, goat cheese, and a flaky crust.",
        category: "brunch",
        ingredients: ["Spinach", "Goat cheese", "Eggs", "Cream", "Pie crust"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Shrimp Avocado Toast",
        price: 13,
        description: "Sourdough toast topped with shrimp, smashed avocado, and a sprinkle of chili flakes.",
        category: "brunch",
        ingredients: ["Sourdough bread", "Shrimp", "Avocado", "Chili flakes", "Lemon juice"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Grilled Salmon",
        price: 18,
        description: "Fresh salmon fillet grilled to perfection, served with a side of lemon butter sauce.",
        category: "dinner",
        ingredients: ["Salmon", "Lemon", "Butter", "Garlic", "Parsley"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Eggplant Parmesan",
        price: 14,
        description: "Layers of breaded eggplant, marinara sauce, and melted mozzarella cheese.",
        category: "dinner",
        ingredients: ["Eggplant", "Marinara sauce", "Mozzarella", "Parmesan cheese", "Breadcrumbs"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Steak with Garlic Mashed Potatoes",
        price: 22,
        description: "Juicy grilled steak served with creamy garlic mashed potatoes and sautéed vegetables.",
        category: "dinner",
        ingredients: ["Steak", "Potatoes", "Garlic", "Butter", "Vegetables"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Vegetarian Stuffed Peppers",
        price: 15,
        description: "Bell peppers stuffed with quinoa, black beans, and vegetables, topped with melted cheese.",
        category: "dinner",
        ingredients: ["Bell peppers", "Quinoa", "Black beans", "Vegetables", "Cheese"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Garlic Butter Shrimp Pasta",
        price: 16,
        description: "Spaghetti tossed in garlic butter sauce with shrimp, parsley, and a sprinkle of Parmesan.",
        category: "dinner",
        ingredients: ["Spaghetti", "Shrimp", "Garlic", "Butter", "Parmesan cheese"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Grilled Chicken Caesar Salad",
        price: 12,
        description: "Classic Caesar salad topped with grilled chicken breast and crispy croutons.",
        category: "lunch",
        ingredients: ["Chicken breast", "Romaine lettuce", "Caesar dressing", "Parmesan", "Croutons"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Vegetable Stir-Fry with Tofu",
        price: 10,
        description: "A medley of fresh vegetables stir-fried with tofu in a savory soy sauce.",
        category: "lunch",
        ingredients: ["Tofu", "Bell peppers", "Broccoli", "Carrots", "Soy sauce"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Turkey Club Sandwich",
        price: 11,
        description: "Triple-layer sandwich with turkey, bacon, lettuce, tomato, and mayonnaise.",
        category: "lunch",
        ingredients: ["Turkey", "Bacon", "Lettuce", "Tomato", "Mayonnaise", "Bread"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Margherita Panini",
        price: 9,
        description: "Toasted panini with fresh mozzarella, tomatoes, and basil pesto.",
        category: "lunch",
        ingredients: ["Bread", "Mozzarella", "Tomato", "Basil pesto"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Beef Burrito Bowl",
        price: 13,
        description: "A hearty bowl with seasoned beef, rice, black beans, and fresh salsa.",
        category: "lunch",
        ingredients: ["Beef", "Rice", "Black beans", "Salsa", "Avocado"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Loaded Nachos",
        price: 8,
        description: "Crispy tortilla chips topped with melted cheese, jalapeños, salsa, and sour cream.",
        category: "snack",
        ingredients: ["Tortilla chips", "Cheddar cheese", "Jalapeños", "Salsa", "Sour cream"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Chicken Wings",
        price: 10,
        description: "Juicy chicken wings tossed in your choice of buffalo, BBQ, or honey mustard sauce.",
        category: "snack",
        ingredients: ["Chicken wings", "Buffalo sauce", "BBQ sauce", "Honey mustard"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Caprese Skewers",
        price: 7,
        description: "Mini skewers with cherry tomatoes, mozzarella balls, and fresh basil drizzled with balsamic glaze.",
        category: "snack",
        ingredients: ["Cherry tomatoes", "Mozzarella", "Basil", "Balsamic glaze"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Mini Sliders",
        price: 12,
        description: "Three mini burgers served with cheese, pickles, and a side of ketchup.",
        category: "snack",
        ingredients: ["Beef patties", "Cheddar cheese", "Pickles", "Mini burger buns", "Ketchup"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Stuffed Mushroom Bites",
        price: 9,
        description: "Bite-sized mushrooms stuffed with cream cheese, herbs, and breadcrumbs, baked to golden perfection.",
        category: "snack",
        ingredients: ["Mushrooms", "Cream cheese", "Breadcrumbs", "Parsley", "Garlic"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Lemon Iced Tea",
        price: 4,
        description: "A refreshing blend of black tea with a zesty lemon twist, served chilled.",
        category: "cold",
        ingredients: ["Black tea", "Lemon juice", "Ice", "Sugar"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Cold Brew Coffee",
        price: 5,
        description: "Smooth and bold coffee brewed cold for an energizing experience.",
        category: "cold",
        ingredients: ["Coffee beans", "Water", "Ice"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Mint Lemonade",
        price: 4,
        description: "Crisp lemonade infused with fresh mint leaves for a cooling taste.",
        category: "cold",
        ingredients: ["Lemon juice", "Mint leaves", "Sugar", "Ice", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Iced Chai Latte",
        price: 5,
        description: "Spiced chai tea mixed with milk and served over ice for a creamy treat.",
        category: "cold",
        ingredients: ["Chai tea", "Milk", "Ice", "Sugar"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Peach Iced Tea",
        price: 4,
        description: "Sweet and fruity iced tea infused with natural peach flavors.",
        category: "cold",
        ingredients: ["Black tea", "Peach syrup", "Ice", "Sugar"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Espresso",
        price: 3,
        description: "A bold and rich shot of pure espresso for coffee enthusiasts.",
        category: "hot",
        ingredients: ["Coffee beans", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Cappuccino",
        price: 4,
        description: "A creamy delight with espresso, steamed milk, and a frothy milk topping.",
        category: "hot",
        ingredients: ["Coffee beans", "Milk"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Green Tea",
        price: 3,
        description: "Soothing and healthy green tea with a mild, refreshing flavor.",
        category: "hot",
        ingredients: ["Green tea leaves", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Hot Chocolate",
        price: 4,
        description: "Rich and indulgent hot chocolate made with creamy milk and cocoa.",
        category: "hot",
        ingredients: ["Milk", "Cocoa powder", "Sugar"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Chamomile Tea",
        price: 3,
        description: "Relaxing chamomile tea perfect for unwinding after a long day.",
        category: "hot",
        ingredients: ["Chamomile flowers", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Orange Juice",
        price: 4,
        description: "Freshly squeezed orange juice, packed with vitamin C.",
        category: "fresh",
        ingredients: ["Oranges"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Tropical Smoothie",
        price: 5,
        description: "A creamy smoothie with mango, pineapple, and a hint of coconut.",
        category: "fresh",
        ingredients: ["Mango", "Pineapple", "Coconut milk"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Strawberry Banana Shake",
        price: 5,
        description: "A sweet and refreshing shake made with strawberries and bananas.",
        category: "fresh",
        ingredients: ["Strawberries", "Banana", "Milk"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Green Detox Juice",
        price: 6,
        description: "A revitalizing mix of kale, green apple, and cucumber.",
        category: "fresh",
        ingredients: ["Kale", "Green apple", "Cucumber"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Watermelon Cooler",
        price: 4,
        description: "Chilled watermelon juice with a splash of lime for a refreshing drink.",
        category: "fresh",
        ingredients: ["Watermelon", "Lime"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Chardonnay",
        price: 8,
        description: "A crisp and refreshing white wine with hints of citrus and oak.",
        category: "alcohol",
        ingredients: ["Grapes"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Cabernet Sauvignon",
        price: 10,
        description: "A bold and rich red wine with notes of blackcurrant and vanilla.",
        category: "alcohol",
        ingredients: ["Grapes"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Pale Ale",
        price: 6,
        description: "A golden craft beer with a balanced hop and malt profile.",
        category: "alcohol",
        ingredients: ["Barley", "Hops", "Yeast", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Stout Beer",
        price: 7,
        description: "A dark and creamy beer with rich flavors of coffee and chocolate.",
        category: "alcohol",
        ingredients: ["Barley", "Hops", "Yeast", "Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Rosé Wine",
        price: 9,
        description: "A delicate and aromatic rosé with notes of strawberry and peach.",
        category: "alcohol",
        ingredients: ["Grapes"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Mojito",
        price: 9,
        description: "A refreshing blend of white rum, fresh mint leaves, lime juice, sugar, and sparkling water.",
        category: "cocktail",
        ingredients: ["White Rum", "Mint Leaves", "Lime Juice", "Sugar", "Sparkling Water"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Margarita",
        price: 10,
        description: "A classic cocktail made with tequila, lime juice, and triple sec, served with a salted rim.",
        category: "cocktail",
        ingredients: ["Tequila", "Lime Juice", "Triple Sec", "Salt"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Old Fashioned",
        price: 12,
        description: "A timeless mix of bourbon, sugar, bitters, and a twist of orange peel.",
        category: "cocktail",
        ingredients: ["Bourbon", "Sugar", "Bitters", "Orange Peel"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Piña Colada",
        price: 11,
        description: "A tropical blend of rum, coconut cream, and pineapple juice, served chilled.",
        category: "cocktail",
        ingredients: ["Rum", "Coconut Cream", "Pineapple Juice"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Espresso Martini",
        price: 13,
        description: "A modern favorite combining vodka, espresso, coffee liqueur, and a touch of sugar.",
        category: "cocktail",
        ingredients: ["Vodka", "Espresso", "Coffee Liqueur", "Sugar"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Margarita",
        price: 10,
        description: "Classic Italian pizza with simple and fresh ingredients.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Basílico"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Pepperoni",
        price: 12,
        description: "A delicious pizza topped with pepperoni and cheese.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Pepperoni"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Quattro Formaggi",
        price: 13,
        description: "A rich and cheesy pizza made with four types of cheese.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Parmesano", "Gorgonzola", "Fontina"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Diavola",
        price: 14,
        description: "Spicy pizza topped with salami for an extra kick.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Salami picante"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Capricciosa",
        price: 13,
        description: "Loaded with ham, mushrooms, and artichokes.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Jamón", "Champiñones", "Alcachofas", "Aceitunas"],
        image: "add image later",
        video: "add video later",
        vegetarian: false,
    },
    {
        name: "Pizza Vegetariana",
        price: 9,
        description: "A fresh and healthy vegetarian pizza with mixed vegetables.",
        category: "Pizzas",
        ingredients: ["Harina de trigo", "Tomate", "Mozzarella", "Verduras mixtas"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Agua con gas",
        price: 3,
        description: "Refreshing sparkling water to quench your thirst.",
        category: "Bebidas",
        ingredients: ["Agua"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Coca-Cola",
        price: 2,
        description: "Classic Coca-Cola with a sweet and fizzy taste.",
        category: "Bebidas",
        ingredients: ["Agua", "Azúcar", "Cafeína"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
        dateAdded: new Date()
    },
    {
        name: "Fanta Naranja",
        price: 2,
        description: "Fruity and refreshing orange-flavored soft drink.",
        category: "Bebidas",
        ingredients: ["Agua", "Azúcar", "Sabor a naranja"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Sprite",
        price: 2,
        description: "Lemon-lime soda with a crisp, clean taste.",
        category: "Bebidas",
        ingredients: ["Agua", "Azúcar", "Sabor a limón"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Té Helado",
        price: 3,
        description: "Iced tea with a touch of lemon for a refreshing drink.",
        category: "Bebidas",
        ingredients: ["Té", "Azúcar", "Limón"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    },
    {
        name: "Agua sin gas",
        price: 2,
        description: "Pure, non-sparkling water for hydration.",
        category: "Bebidas",
        ingredients: ["Agua"],
        image: "add image later",
        video: "add video later",
        vegetarian: true,
    }

];

// Create Product documents from the products array
const productDocuments = products.map(product => new Product(product));

// Set mongoose options for queries
mongoose.set('strictQuery', true);

// Main function to seed the database
(async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(mongoDb);

        // Check if there are existing products in the database
        const allProduct = await Product.find();
        if (allProduct.length) {
            // If products exist, drop the collection
            await Product.collection.drop();
        }

        // Insert the new product documents into the database
        await Product.insertMany(productDocuments);
        console.log('Database Created'); // Log a success message
    } catch (err) {
        console.error(`Error: ${err}`); // Log any errors that occur
    } finally {
        mongoose.disconnect(); // Disconnect from the database after operations are complete
    }
})();
